package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.User;
import model.Component;
import model.RepairService;
import model.vehicle.Vehicle;

public class addRepairServiceFrm extends javax.swing.JDialog {
    private Home home;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> cbVehicle_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtVehicle_license_number;
    private javax.swing.JTextField txtVehicle_owner;
    private javax.swing.JTextField txtComponent_price;
    private javax.swing.JTextField txtRepair_service_id;
    private javax.swing.JTextField txtRepair_service_created_date;
    private javax.swing.JTextField txtVehicle_owner_phone;
    private javax.swing.JTextField txtComponent_quantity;
    private javax.swing.JTextField txtRepair_service;
    // End of variables declaration//GEN-END:variables

    public addRepairServiceFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        home = (Home) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVehicle_license_number = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVehicle_owner = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRepair_service = new javax.swing.JTextField();
        txtVehicle_owner_phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtComponent_quantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtComponent_price = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRepair_service_created_date = new javax.swing.JTextField();
        cbVehicle_type = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtRepair_service_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("NHẬP THÔNG TIN");

        jLabel2.setText("Biển số xe:");

        txtVehicle_license_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBSXActionPerformed(evt);
            }
        });

        jLabel3.setText("Loại xe:");

        jLabel4.setText("Chủ sở hữu:");

        txtVehicle_owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChuSoHuuActionPerformed(evt);
            }
        });

        jLabel7.setText("Sửa chữa:");

        txtRepair_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuaChuaActionPerformed(evt);
            }
        });

        txtVehicle_owner_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        jLabel6.setText("SĐT:");

        jLabel8.setText("Số lượng:");

        jLabel9.setText("Đơn giá:");

        txtComponent_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        addBtn.setText("Thêm");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        cancelBtn.setText("Hủy bỏ");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ngày sửa:");

        txtRepair_service_created_date.setToolTipText("dd/MM/yyyy");
        txtRepair_service_created_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySuaActionPerformed(evt);
            }
        });

        cbVehicle_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe ga", "Xe số", "Xe côn" }));

        jLabel5.setText("ID:");

        txtRepair_service_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel5))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtVehicle_license_number)
                                                        .addComponent(txtRepair_service)
                                                        .addComponent(txtVehicle_owner_phone)
                                                        .addComponent(txtVehicle_owner)
                                                        .addComponent(cbVehicle_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtRepair_service_id, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(addBtn)
                                                                .addGap(87, 87, 87)
                                                                .addComponent(cancelBtn))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(txtComponent_quantity)
                                                                .addComponent(txtComponent_price)
                                                                .addComponent(txtRepair_service_created_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(142, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtRepair_service_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtVehicle_license_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(cbVehicle_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtVehicle_owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtVehicle_owner_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtRepair_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtRepair_service_created_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtComponent_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtComponent_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addBtn)
                                        .addComponent(cancelBtn))
                                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBSXActionPerformed

    private void txtChuSoHuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChuSoHuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChuSoHuuActionPerformed

    private void txtSuaChuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuaChuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuaChuaActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String repair_service_id = "";

        String vehicle_license_number = "";
        String vehicle_type = "";
        String user_name = "";
        String user_phone = "";
        String repair_service = "";
        int component_quantity = 0;
        double component_price = 0;
        Date repair_created_date = null;
        if (validParameter(
                getSafetyInputString(txtRepair_service_id),
                getSafetyInputString(txtVehicle_license_number),
                getSafetyInputString(cbVehicle_type),
                getSafetyInputString(txtVehicle_owner),
                getSafetyInputString(txtVehicle_owner_phone),
                getSafetyInputString(txtRepair_service),
                getSafetyInputString(txtComponent_price),
                getSafetyInputString(txtComponent_quantity),
                getSafetyInputString(txtRepair_service_created_date))
            && parsePrice(
                component_price, getSafetyInputString(txtComponent_price))
            && parseCreatedDate(
                repair_created_date,getSafetyInputString(txtRepair_service_created_date))

            && parseQuantity(component_quantity,getSafetyInputString(txtComponent_quantity))

            ) {

            Component component = new Component(repair_service, component_quantity, component_price);
            User user = new User(user_name, user_phone);
            Vehicle vehicle = new Vehicle();
            RepairService qly = new RepairService( component, vehicle, repair_created_date, repair_service_id);

            home.addVehicle(qly);
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");

//            txtID.setText("");
//            txtBSX.setText("");
//            txtChuSoHuu.setText("");
//            txtSDT.setText("");
//            txtSuaChua.setText("");
//            txtSoLuong.setText("");
//            txtDonGia.setText("");
//            txtNgaySua.setText("");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void txtNgaySuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySuaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private boolean validParameter(
            String repair_service_id,
            String vehicle_license_number,
            String vehicle_type,
            String user_name,
            String user_phone,
            String repair_service,
            String component_quantity,
            String component_price,
            String repair_created_date){
        if (!repair_service_id.isEmpty()
                && !vehicle_license_number.isEmpty()
                && !vehicle_type.isEmpty()
                && !user_name.isEmpty()
                && !user_phone.isEmpty()
                && !repair_service.isEmpty()
                && !component_quantity.isEmpty()
                && !component_price.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin!");
        }

        if (!home.checkRepair_service_id(repair_service_id)) {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Mã chăm sóc đã tồn tại trong danh sách!");
        }

        if (!user_name.matches("[\\p{L} ]+")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tên không được chứa kí tự số và các kí tự đặc biệt!");
        }

        if(user_phone.length() == 10) {
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "SĐT không hợp lệ!");
        }
        return false;
    }

    private boolean parseQuantity(int quantity, String quantity_str){
        try {
            quantity = Integer.parseInt(txtComponent_quantity.getText().trim());
            if(quantity <= 0) {
                throw new NumberFormatException();
            }
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số nguyên dương và không chứ kí tự chữ!");
        }
        return false;
    }

    private boolean parsePrice(double price, String price_str){
        try {
            price = Double.parseDouble(price_str);
            if(price <= 0) {
                throw new NumberFormatException();
            }
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Đơn giá phải lớn hơn 0 và không chứa kí tự chữ!");
        }
        return false;
    }

    private boolean parseCreatedDate(Date repair_created_date, String repair_created_date_str){
        try {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");;
            repair_created_date = dateFormat.parse(repair_created_date_str);
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ngày chăm sóc không hợp lệ!");
        }
        return false;
    }



    private static String getSafetyInputString(javax.swing.JTextField txt){
        return txt.getText().trim();
    }

    private static String getSafetyInputString(javax.swing.JComboBox<String> txt){
        return txt.getSelectedItem().toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRepairServiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRepairServiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRepairServiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRepairServiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addRepairServiceFrm dialog = new addRepairServiceFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

}
